export const formatCurrency = (number) => {
  const CURRENCY_FORMATTER = new Intl.NumberFormat('en-US', {
    currency: 'USD',
    style: 'currency',
  });
  return CURRENCY_FORMATTER.format(number);
};



export const categories = [ 'products',  'Hoodies', 'Shirts', 'Jeans' ,'Trendy' , 'Arrival' ];

export  const links = [
  // { name: 'cities', link: '/cities' },
  { name: 'About', link: '/about' },
  { name: 'Contact', link: '/contact' },
  { name: 'Support', link: '/support' },
];

export const subLinks = ['Shirts', 'Jeans', 'Hoodies',   'Trendy' , 'Arrival'];

export  const cityOptions = [
  { en: "Moscow", ru: "Москва", key: "moscow",  description:'Amazing material with high quality ' , link :'/city=moscow',  img: '/images/cities/moscow.jpg',},
  { en: "Saint Petersburg", ru: "Санкт-Петербург", key: "saint-petersburg" , description:'Amazing material with high quality ' , link :'/city=saint-petersburg',  img: '/images/cities/moscow.jpg',},
  { en: "Novosibirsk", ru: "Новосибирск", key: "novosibirsk"  , description:'Amazing material with high quality ' , link :'/city=novosibirsk',  img: '/images/cities/moscow.jpg',},
  { en: "Yekaterinburg", ru: "Екатеринбург", key: "yekaterinburg"  , description:'Amazing material with high quality ' , link :'/city=yekaterinburg',  img: '/images/cities/moscow.jpg',},
  { en: "Kazan", ru: "Казань", key: "kazan"  , description:'Amazing material with high quality ' , link :'/city=kazan',  img: '/images/cities/moscow.jpg',},
  { en: "Nizhny Novgorod", ru: "Нижний Новгород", key: "nizhny-novgorod"  ,  description:'Amazing material with high quality ', link :'/city=nizhny-novgorod',  img: '/images/cities/moscow.jpg',},
  { en: "Samara", ru: "Самара", key: "samara"  , description:'Amazing material with high quality ' , link :'/city=samara',  img: '/images/cities/moscow.jpg',},
  { en: "Rostov-on-Don", ru: "Ростов-на-Дону", key: "rostov-on-don"  , description:'Amazing material with high quality' , link :'/city=rostov-on-don',  img: '/images/cities/moscow.jpg',},
  { en: "Chelyabinsk", ru: "Челябинск", key: "chelyabinsk"  , description:'Amazing material with high quality ' , link :'/city=chelyabinsk',  img: '/images/cities/moscow.jpg',},
  { en: "Omsk", ru: "Омск", key: "omsk", description:'Amazing material with high quality ' , link :'/city=omsk',  img: '/images/cities/moscow.jpg',},
  { en: "Ufa", ru: "Уфа", key: "ufa"  , description:'Amazing material with high quality' , link :'/city=ufa',  img: '/images/cities/moscow.jpg',},
  { en: "Krasnoyarsk", ru: "Красноярск", key: "krasnoyarsk"  , description:'Amazing material with high quality ' , link :'/city=krasnoyarsk',  img: '/images/cities/moscow.jpg',},
  { en: "Voronezh", ru: "Воронеж", key: "voronezh"  , description:'Amazing material with high quality' , link :'/city=voronezh',  img: '/images/cities/moscow.jpg',},
  { en: "Perm", ru: "Пермь", key: "perm"  , description:'Amazing material with high quality ' , link :'/city=perm',  img: '/images/cities/moscow.jpg',},
  { en: "Volgograd", ru: "Волгоград", key: "volgograd"  , description:'Amazing material with high quality ' , link :'/city=volgograd',  img: '/images/cities/moscow.jpg',},
  { en: "Tyumen", ru: "Тюмень", key: "tyumen" , description:'Amazing material with high quality ' , link :'/city=tyumen',  img: '/images/cities/moscow.jpg',},
];

// export const SLIDES = [
//   {
//     img: '/images/cities/moscow.jpg',
//     title: 'Москва',
//     link: '/city?moscow',
//     description:''
//   },
//   {
//     img: '/images/cities/saint-petersburg.jpg',
//     title: 'Санкт-Петербург',
//     link: '/city?moscow',
//   },
//   {
//     img: '/images/cities/novosibirsk.jpg',
//     title: 'Новосибирск',
//     link: '/city?moscow',
//   },
//   {
//     img: '/images/cities/yekaterinburg.jpg',
//     title: 'Екатеринбург',
//     link: '/city?moscow',
//   },
//   {
//     img: '/images/cities/kazan.jpg',
//     title: 'Казань',
//     link: '/city?moscow',
//   },
//   {
//     img: '/images/cities/nizhny-novgorod.jpg',
//     title: 'Нижний Новгород',
//     link: '/city?moscow',
//   },
//   {
//     img: '/images/cities/samara.jpg',
//     title: 'Самара',
//     link: '/city?moscow',
//   },
//   {
//     img: '/images/cities/omsk.jpg',
//     title: 'Омск',
//     link: '/city?moscow',
//   },
//   {
//     img: '/images/cities/rostov-on-don.jpg',
//     title: 'Ростов-на-Дону',
//     link: '/city?moscow',
//   },
//   {
//     img: '/images/cities/chelyabinsk.jpg',
//     title: 'Челябинск',
//     link: '/city?moscow',
//   },
//   {
//     img: '/images/cities/ufa.jpg',
//     title: 'Уфа',
//     link: '/cities/ufa'
//   },
//   {
//     img: '/images/cities/volgograd.jpg',
//     title: 'Волгоград',
//     link: '/cities/volgograd'
//   },
// ];


// Helper function to generate unique IDs
let productIdCounter = 1;

export const products = Array.from({ length: 10 }, (_, i) => ({
  id: 100 + i,
  title: [
    "Modern Studio in City Center",
    "Luxury 3-Bedroom Penthouse",
    "Cozy 1-Room Apartment Near Park",
    "Family-Friendly 4-Room Flat",
    "Business-Class 2-Room Apartment",
    "Charming Loft-Style Apartment",
    "New Renovated 3-Room Flat",
    "Premium Studio with Panoramic Views",
    "Comfortable 2-Level Duplex",
    "Historic District 1-Room Apartment"
  ][i],
  descriptionShort: [
    "Perfect for solo travelers or couples, fully equipped with modern amenities",
    "Spacious luxury accommodation with premium finishes and city views",
    "Quiet location ideal for long stays with green park nearby",
    "Great for large families with children, playground in courtyard",
    "Ideal for business travelers with fast internet and workspace",
    "Unique industrial-chic design with exposed brick walls",
    "Fresh renovation with smart home technology",
    "High-floor apartment with floor-to-ceiling windows",
    "Two-level living space with private terrace",
    "Character apartment in heritage building"
  ][i],
  
  checkInConditions: {
    documents: i % 2 ? "Passport required" : "Digital registration available",
    checkOutTime: i < 5 ? "11:00" : "12:00",
    partiesAllowed: i === 3,
    roundTheClockCheckIn: i % 3 === 0,
    petsAllowed: i > 7,
    smokingAllowed: false,
    prepaymentRequired: i % 4 === 0
  },

  apartmentParameters: {
    apartmentType: ["Studio", "1-room", "2-room", "3-room", "Penthouse"][i % 5],
    maxGuests: [2, 4, 3, 6, 2, 4, 5, 2, 6, 3][i],
    singleBeds: [1, 0, 1, 2, 1, 0, 1, 1, 2, 1][i],
    doubleBeds: [1, 2, 1, 2, 1, 2, 2, 1, 2, 1][i],
    floorAndTotalFloors: `${i + 2}/${[5, 9, 12, 25, 3, 7, 16, 24, 2, 6][i]}`,
    area: {
      total: [35, 85, 42, 110, 45, 55, 75, 40, 90, 38][i],
      living: [20, 35, 25, 45, 22, 30, 40, 18, 50, 20][i],
      kitchen: [15, 20, 17, 25, 13, 25, 15, 12, 20, 18][i]
    },
    bathroom: i % 2 ? "Combined" : "Separate",
    buildingType: ["Monolithic", "Brick", "Panel", "Stalin-era", "Modern"][i % 5],
    windowView: ["Street", "Courtyard", "Park", "City view", "River view"][i % 5],
    renovation: ["Euro-style", "Modern", "Soviet-era", "Designer", "Luxury"][i % 5],
    balconyType: i % 3 ? "None" : ["French", "Standard", "Loggia"][i % 3],
    parkingAvailable: i > 2,
    parkingType: ["Underground", "Guarded", "Street", "None"][i % 4]
  },

  amenities: [
    ["Wi-Fi", "Smart TV", "Air conditioning", "Washing machine"],
    ["Wi-Fi", "Cable TV", "Dishwasher", "Dryer"],
    ["Wi-Fi", "Smart TV", "Microwave", "Coffee maker"],
    ["Wi-Fi", "Game console", "Baby cot", "High chair"],
    ["Wi-Fi", "Office desk", "Printer", "Scanner"],
    ["Wi-Fi", "Sound system", "Record player", "Art collection"],
    ["Wi-Fi", "Smart home system", "Robot vacuum", "Mood lighting"],
    ["Wi-Fi", "Home theater", "Jacuzzi", "Sauna"],
    ["Wi-Fi", "BBQ equipment", "Outdoor furniture", "Fire pit"],
    ["Wi-Fi", "Vintage furniture", "Library", "Fireplace"]
  ][i],

  houseDescription: [
    ["Elevator", "Security", "Playground", "Fitness center"],
    ["Concierge", "Underground parking", "Pool", "Spa"],
    ["24/7 security", "Package room", "Bike storage"],
    ["Green courtyard", "Pet area", "BBQ zone"],
    ["Business center", "Conference rooms", "Dry cleaning"],
    ["Art installations", "Roof terrace", "Co-working space"],
    ["Electric car charging", "Recycling system", "Smart locks"],
    ["Wine cellar", "Private cinema", "Staff quarters"],
    ["Vegetable garden", "Compost area", "Rainwater collection"],
    ["Historical preservation", "Original details", "Museum nearby"]
  ][i],
  city: i % 2 === 0 ? "moscow" : "tyumen",

  mapInfo: {
    address: [
      "Lenina 15, Central District",
      "Sovetskaya 42, Business Quarter",
      "Parkovaya 8, Green Zone",
      "Naberezhnaya 3, Riverside",
      "Promyshlennaya 25, Industrial Area",
      "Istoricheskaya 7, Old Town",
      "Novaya 12, New Development",
      "Vysotnaya 1, Skyscraper District",
      "Sadovaya 18, Garden Suburb",
      "Turisticheskaya 5, Hotel Zone"
    ][i],
    note: "© Yandex, Terms of Use",
    approximateDistance: [
      "300m to metro",
      "500m to supermarket",
      "200m to park",
      "1km to downtown",
      "50m to bus stop",
      "700m to museum",
      "400m to fitness center",
      "100m to river",
      "600m to market",
      "800m to hospital"
    ][i],
    district: [
      "Central", "Business", "Residential", "Historic",
      "Industrial", "Tourist", "New Development", 
      "Riverside", "Suburban", "Mixed-use"
    ][i]
  },

  kitchen: [
    ["Induction stove", "Oven", "Dishwasher", "Coffee machine"],
    ["Gas stove", "Microwave", "Electric kettle", "Toaster"],
    ["Mini-kitchen", "Combination oven", "Single burner"],
    ["Full kitchen", "Pantry", "Wine cooler"],
    ["Compact kitchen", "Nespresso machine", "Bar setup"],
    ["Open kitchen", "Pizza oven", "Espresso maker"],
    ["Smart kitchen", "Voice-controlled appliances"],
    ["Chef's kitchen", "Professional equipment"],
    ["Outdoor kitchen", "BBQ grill", "Smoker"],
    ["Vintage kitchen", "Retro appliances"]
  ][i],

  infrastructure: [
    ["Supermarket", "Pharmacy", "Cafe", "ATM"],
    ["Mall", "Cinema", "Restaurants", "Fitness club"],
    ["Park", "Playground", "Bike paths", "Library"],
    ["School", "Kindergarten", "Clinic", "Post office"],
    ["Business center", "Coworking", "Print shop"],
    ["Museum", "Gallery", "Theater", "Antique shops"],
    ["Yoga studio", "Organic market", "Juice bar"],
    ["Luxury boutiques", "Fine dining", "Spa"],
    ["Farmers market", "Craft stores", "Public garden"],
    ["Tourist info", "Souvenir shops", "Guided tours"]
  ][i],

  images: Array.from({ length: 5 }, (_, imgIndex) => ({
    filename: `apt${100 + i}_img${imgIndex + 1}.jpg`,
    caption: [
      ["Living room", "Bedroom", "Kitchen", "Bathroom", "View"],
      ["Main area", "Master suite", "Dining", "Balcony", "Building"],
      ["Entrance", "Workspace", "Storage", "Details", "Neighborhood"],
      ["Daylight", "Night view", "Layout", "Amenities", "Map"],
      ["Exterior", "Lobby", "Facilities", "Parking", "Security"]
    ][i % 5][imgIndex],
    url: `/images/apt${100 + i}/image${imgIndex + 1}.jpg`
  }))
}));

















// Product data
// export const products = [
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-slip-on-shoes',
//     name: 'Acme Slip-On Shoes',
//     price: 45.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//     ],
//     category: 'Footwear',
//     sizes: sizesForShoes,
//     description: 'Comfortable and stylish slip-on shoes for everyday wear.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-choice-t-shirt',
//     name: 'Acme Choice T-Shirt',
//     price: 30.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A classic T-shirt made from premium cotton for ultimate comfort.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-drawstring-bag',
//     name: 'Acme Drawstring Bag',
//     price: 12.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/bag.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/bag.png' },
//     ],
//     category: 'Bags',
//     sizes: sizesForTshirt,
//     description: 'Lightweight and durable drawstring bag for your daily essentials.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-keyboard',
//     name: 'Acme Keyboard',
//     price: 150.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//     ],
//     category: 'Electronics',
//     sizes: sizesForTshirt,
//     description: 'Mechanical keyboard with RGB lighting for gamers and typists.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-prism-t-shirt',
//     name: 'Acme Prism T-Shirt',
//     price: 25.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A vibrant T-shirt with a unique prism design.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-slip-on-shoes',
//     name: 'Acme Slip-On Shoes',
//     price: 45.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//     ],
//     category: 'Footwear',
//     sizes: sizesForShoes,
//     description: 'Comfortable and stylish slip-on shoes for everyday wear.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-choice-t-shirt',
//     name: 'Acme Choice T-Shirt',
//     price: 30.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A classic T-shirt made from premium cotton for ultimate comfort.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-drawstring-bag',
//     name: 'Acme Drawstring Bag',
//     price: 12.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/bag.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/bag.png' },
//     ],
//     category: 'Bags',
//     sizes: sizesForTshirt,
//     description: 'Lightweight and durable drawstring bag for your daily essentials.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-keyboard',
//     name: 'Acme Keyboard',
//     price: 150.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//     ],
//     category: 'Electronics',
//     sizes: sizesForTshirt,
//     description: 'Mechanical keyboard with RGB lighting for gamers and typists.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-prism-t-shirt',
//     name: 'Acme Prism T-Shirt',
//     price: 25.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A vibrant T-shirt with a unique prism design.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
// ];

// export const shirts = [
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-slim-fit-shirt',
//     name: 'Acme Slim Fit Shirt',
//     price: 35.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A slim-fit shirt for a modern and stylish look.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-cotton-shirt',
//     name: 'Acme Cotton Shirt',
//     price: 28.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'Soft and breathable cotton shirt for all-day comfort.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-oversized-shirt',
//     name: 'Acme Oversized Shirt',
//     price: 32.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A trendy oversized shirt for a relaxed fit.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
// ];

// export const hoodies = [
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-pullover-hoodie',
//     name: 'Acme Pullover Hoodie',
//     price: 50.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/hoodie.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Hoodies',
//     sizes: sizesForTshirt,
//     description: 'A cozy pullover hoodie for chilly days.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-zip-up-hoodie',
//     name: 'Acme Zip-Up Hoodie',
//     price: (55.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/hoodie.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Hoodies',
//     sizes: sizesForTshirt,
//     description: 'A versatile zip-up hoodie for a casual yet stylish look.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-fleece-hoodie',
//     name: 'Acme Fleece Hoodie',
//     price: (60.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/hoodie.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Hoodies',
//     sizes: sizesForTshirt,
//     description: 'A warm fleece hoodie for cold winter days.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },

// ];

// export const jeans = [
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-slim-fit-jeans',
//     name: 'Acme Slim Fit Jeans',
//     price: (60.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'Blue', url: '/images/bag.png' },
//     ],
//     category: 'Jeans',
//     sizes: sizesForJeans,
//     description: 'Slim-fit jeans for a modern and sleek appearance.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-straight-leg-jeans',
//     name: 'Acme Straight Leg Jeans',
//     price: (65.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'Blue', url: '/images/bag.png' },
//     ],
//     category: 'Jeans',
//     sizes: sizesForJeans,
//     description: 'Classic straight-leg jeans for a timeless look.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-relaxed-fit-jeans',
//     name: 'Acme Relaxed Fit Jeans',
//     price: (70.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'Blue', url: '/images/bag.png' },
//     ],
//     category: 'Jeans',
//     sizes: sizesForJeans,
//     description: 'Comfortable relaxed-fit jeans for a casual look.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
// ];

// export const shoes = [
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-running-shoes',
//     name: 'Acme Running Shoes',
//     price: (80.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//     ],
//     category: 'Footwear',
//     sizes: sizesForShoes,
//     description: 'Lightweight and durable running shoes for athletes.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-casual-shoes',
//     name: 'Acme Casual Shoes',
//     price: (70.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//     ],
//     category: 'Footwear',
//     sizes: sizesForShoes,
//     description: 'Stylish and comfortable casual shoes for everyday wear.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-hiking-shoes',
//     name: 'Acme Hiking Shoes',
//     price: (90.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'Brown', url: '/images/bag.png' },
//     ],
//     category: 'Footwear',
//     sizes: sizesForShoes,
//     description: 'Durable hiking shoes for outdoor adventures.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
// ];

// export const accessories = [
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-leather-belt',
//     name: 'Acme Leather Belt',
//     price: (25.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/bag.png' },
//       { color: 'Brown', url: '/images/bag.png' },
//     ],
//     category: 'Accessories',
//     sizes: ['S', 'M', 'L', 'XL'],
//     description: 'A premium leather belt for a polished look.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-wool-scarf',
//     name: 'Acme Wool Scarf',
//     price: (30.0),
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/bag.png' },
//       { color: 'Gray', url: '/images/bag.png' },
//     ],
//     category: 'Accessories',
//     sizes: ['One Size'],
//     description: 'A warm wool scarf for winter comfort.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   }, {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   }, {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
//   {
//     id: productIdCounter++,
//     handlerName: 'acme-t-shirt',
//     name: 'Acme T-Shirt',
//     price: 20.0,
//     quantity: 1,
//     images: [
//       { color: 'Black', url: '/images/shirt.png' },
//       { color: 'White', url: '/images/bag.png' },
//       { color: 'Blue', url: '/images/hoodie.png' },
//     ],
//     category: 'Shirts',
//     sizes: sizesForTshirt,
//     description: 'A simple and elegant T-shirt for casual outings.',
//   },
// ];

